rmarkdown::render("schedule.Rmd")
rmarkdown::render("wk/wk01.Rmd")
rmarkdown::render("wk/wk02.Rmd")
rmarkdown::render("wk/wk03.Rmd")
rmarkdown::render("wk/wk04.Rmd")
#rmarkdown::render("wk/wk05.Rmd")
#rmarkdown::render("wk/wk06.Rmd")
# rmarkdown::render("wk/wk07.Rmd")
# rmarkdown::render("wk/wk08.Rmd")
# rmarkdown::render("wk/wk09.Rmd")
# rmarkdown::render("wk/wk10.Rmd")
# rmarkdown::render("wk/wk11.Rmd")
# rmarkdown::render("wk/wk12.Rmd")
# rmarkdown::render("wk/wk13.Rmd")
# rmarkdown::render("wk/wk14.Rmd")

