
This is the landing page for <span style="color:teal">**Applied Statistical Methods 1**</span> course taught by [Dr. Robin Donatello](www.norcalbiostat.com)  in Fall 2018. This landing page is used for posting of regular announcements and information for students of the class. 

```{r runallwks, eval=TRUE, echo=FALSE, results='hide', message=FALSE, warning=FALSE}
# source("_render_all_wks.R")
#source("_render_all_lec.R")
#source("_render_all_hw.R")
#rmarkdown::render(notes.Rmd, output_format='html_document')
```

# Announcements

<!--- 
### 12/14/17 - Final Exam. 8-10am. Tehama 108

<span style="color:red">**Office Hours for Finals Week**</span> 

* Tuesday 2-4pm, Holt 155
* Wednesday 1-3pm, Holt 202
* Wednesday 8-9pm, Online Google Hangouts. Over now. Apparently >10 people causes it to crash. I will find another method next time. Much apologies to those who came early but got cut out. 

<span style="color:red">**Allowed Exam Materials**</span> 
All exam materials (except course notes) will be turned in with the exam. Make sure your name is on everything.  

* The [[OFFICIAL]](https://norcalbiostat.github.io/MATH615/FinalDocs/FinalExam_Fall17_Supplemental.pdf) supplemental information and analyses for the Outlook on Life Survey. 
    - Print these pages. Ensure that you understand what models are being fit and how to read the output. You are allowed to write notes on these pages.
    - Be prepared to answer questions about modeling and interpreting these analyses. 
* A calculator
* Your course notes
* An additional 1 page of notes


    
Additional information on this new survey, such as full wording of the question on how the variables were coded can be found in the [[codebook]](https://norcalbiostat.github.io/MATH615/FinalDocs/OOL%20Codebook.pdf) and [[survey questionnaire]](https://norcalbiostat.github.io/MATH615/FinalDocs/OOL%20Questionnaire.pdf). **Do not bring these to the final**. They are for you to use as reference material while you are learning to understand this survey.   

<span style="color:red">**Review List**</span> 
This final exam is comprehensive in that everything in this class builds upon previous topics. 
Here are a list of topics to review. All topics have equal importance, regardless of the time that was spent on each topic during class. 

* Probability
* Creating and interpreting confidence intervals
* Assumptions for statistical methods to be valid
* Generalizability, representativeness, bias, sampling frame
* Statistical Analysis Procedures: 
    - Two-sample T-tests for means and proportions
    - ANOVA and $\chi^{2}$ for multiple samples
    - Linear and Logistic regression.
* Identifying confounders, moderators and covariates. 
* Interpreting regression coefficients and making predictions using models. 
    - from linear and logistic models
    - using continuous and categorical variables


### 12/4/17 - Week 15
* Fill out [This google form](https://goo.gl/forms/o3O43feULJFDGUun2) to provide input as to when I should hold OH during finals week. 
* Poster presentations MW
    - Your poster must be printed and ready for class on Monday. 
    - We will randomly choose people to present on Monday, the rest will present on Wednesday. (I can hold your posters in my office until Wednesday.)
* Build your own [exam questions](hw/roll_your_own.html) - **Due Wednesday**

### 11/27/17 - Week 14
* All Data Camp and Problem set Blackboard learn quizzes due this Friday. No extensions given. 
* Poster building week! See the project page for instructions. 
    - Drafts are due Wednesday, reviews due Friday
    - Suggestions on how to make a nice plot for multivariable models has been added to the project page. 
* Citation information has been updated to Project page (slide 16) on how to cite addhealth, R, and R studio
* See [this abstract](http://www.cpc.unc.edu/projects/addhealth/publications/database/6893) for a demonstration on how to describe using the Add Health data set in an analysis.  



### 11/13/17 - [Week 13](https://norcalbiostat.github.io/MATH315/wk/wk13.html)
* RAT on Logistic Regression - Monday
    - Review the last part of PDS Video 17
    - Read Open Intro 8.4: Intro to Logistic Regression
* Model building
    - Read Open Intro 8.2: Model Selection
* Friday Statistics Seminar. Extra credit opportunity. 
    - Robert Weiss, UCLA Biostatistics. 
    - Talk on comparing the efficacy between two biologic compounds for FDA approval
    - Friday 3:30, refreshments at 3, Holt 175. 
* R Cheat sheets have been added to the FAQ page



### 11/6/17 - [Week 12](https://norcalbiostat.github.io/MATH315/wk/wk12.html)
* Identifying confounders
* Adding and interpreting categorical predictors
* Poster updates
    - Start testing the relationship for your RQ for moderators and confounders. 
    - Homework $\neq$ poster. Don't go overboard, but you are likely to need to do additional analyses for your poster. 
    - Keep your RQ in mind - focus on answering a single RQ. One outcome. 
* **Class Attendance Required**: Due to a large number of people missing class lately, for the rest of the semester I will be taking attendance. You cannot work as a team if you don't bother to show up to class at the same time. 
    - We only have a few weeks left in the semester. This is a critical time in your project development. 

--->

### 11/5/18 - [Week 11](https://norcalbiostat.github.io/MATH315/wk/wk11.html)

* Some final thoughts about regression models
    - explanatory vs predictive
    - how to measure model fit - coefficient of determination $R^2$
    - how outliers can affect the model
* What's the difference between an Observational study and an Experiment? 
    - why can't we make causal statements on observational studies? 
* Buliding multiple variable models 
    - how adding additional measures into a regression model acts as a "control"
    - expressing multiple regression models mathematically
* Confounding variables - how a third variable can "explain" the relationship between two other variables

### 10/29/18 - [Week 10](https://norcalbiostat.github.io/MATH315/wk/wk10.html)

* Open work day on Monday. Finish those assignments! 
* Lecture on Moderation on Wednesday - watch the PDS Video 14 ahead of time. 
* Exam 2 on Friday: Foundations for inference (probability, sampling distribution, confidence intervals, hypothesis testing, choosing appropriate analyses, setting up testable hypothesis, conducting and interpreting hypotheses tests)
    - Practice problems have been posted in Slack. 
    - Virtual OH/Review session is Tuesday 8pm via Zoom. Meeting ID: 306 187 300
        * Connect by computer: https://csuchico.zoom.us/j/306187300
        * Connect by telephone: +1 646 558 8656  or +1 669 900 6833
    - A review session is only as good as the people who attend make it. I will be answering questions and expanding on topics. I won't go through the answer to _every_ question on the practice exam, you have to have tried the problems first. 


### 10/22/18 - [Week 9](https://norcalbiostat.github.io/MATH315/wk/wk09.html)
* Continuing with Bivariate analysis
    - Chi squared test of independence on Monday
    - Correlation on Wednesday (**PDS Video**)
    - Linear regression on Friday (**RAT**)
* Be sure to watch the PDS videos so we can spend most of class time working on the assignment. 
* Additional lecture materials are available for regression
    - Applied Stats Notesbook Chapter 5
* Exam 2 on Statistical Inference next Friday. 


### 10/15/18 - [Week 8](https://norcalbiostat.github.io/MATH315/wk/wk08.html)
* This week is all about Bivariate inference.
    - Hypothesis testing with R on Monday
    - Two sample t-test on Wednesday
    - ANOVA on Friday -- Corresponding PDS video
* RAT on Wednesday (not Monday) 
* BIG assignment! Has multiple parts. Procrastinate and be doomed. 
* Majority of learning statistical content will come from PDS videos. 
    - In class is a recap, highlights, and open work time



### 10/8/18 - [Week 7](https://norcalbiostat.github.io/MATH315/wk/wk07.html)

* Exam 1 handed back on Monday - after some brief comments we'll start talking about point estimates. 
* This week is a lot of "book work". You will learn by reading and participating in class, your assignments are all assigned through Blackboard Learn. 
* Problem set 3.1 and 3.2 should have been officially assigned last week, they are set for being due EOD on Monday. 
    - Reminder: These due dates are so YOU are keeping up with the class. They will stay open until Exam 2, but the sooner you do them the better off you will be in class. 
* The rest of the schedule for the semester has been set. Plan your time accordingly. These assignments will take longer than one evening to complete.
    - I will be working over the next few days to open the rest of the assignments in Blackboard Learn so that they show up on the calendar. 
* There will be no more required peer review of normal assignments directly, you will be reviewing the team's project analysis work. 
    - You will submit HW through Blackboard Learn 
    - I will comment on the documents directly and post to Google Drive for shared learning
    - Your grade is still confidential and will be graded using a rubric in Blackboard learn. 


### 10/1/18 - [Week 6](https://norcalbiostat.github.io/MATH315/wk/wk06.html)

* Monday: Next steps for the project - starting your poster slides. 
* Wednesday: Exam 1. A sample exam is linked on the materials, and posted in Slack over the weekend. 
* Friday: Probability. This is a very brief overview, refer to the OpenIntro textbook and PDS videos for more learning. 

There has been some modifications to the assignments. The research propsal assignment has been cancelled, and the weight of the individual homework assignments has been increased. Be mindful of due dates, and peer review problems. 

If you haven't done so in a while, you might want to check Slack. Especially the #assignments channel. I share important information on there. 

### 9/18/17 - [Week 5](https://norcalbiostat.github.io/MATH315/wk/wk05.html)
* This week we will discuss how to create visualizations to assess the relationship between two variables. 
* Open work days are not optional, your attendance is expected. 
* The bivariate graphing assignment is an individual submission that is peer reviewed- but you do **NOT** get a chance to revise your assignment. This is so I can get it graded and back to you in time for the exam. 
* You should also be working on your project poster preparation slides. The homework assignments are training grounds for you to practice how to create and interpret graphics to explore your research question. The graphs you make for the homework may or may not be directly related to your research question. 


**Reminder**: I have gone through the gradebook and entered in 0's for missing assignments to date. This is done to provide you a better idea of where you stand grade-wise, going into this exam. Quizzes will remain open available up until the test on October 3rd. So if you got a 0 on a Problem set or Data Camp quiz you have time to make up those points. This is also a good way to study for the exam. 


### 9/17/18 - [Week 4](https://norcalbiostat.github.io/MATH315/wk/wk04.html)

The optional revision period to your peer review assignments has been added to the submission instructions on the [[Help page]](help_assignments.html). 

**Writing Research questions**

Your RQ's need to be explicit, and very simple. Is there an association between X and Y? How does X affect Y?
Be as detailed and specific as possible. Ask a question where you can say "Yes" or "No" to. 
You also need to identify exactly what variable in the data set you are going to use to measure X and Y.  

> Is there an association between current age and binge drinking (more than 4 drinks for women and 5 for men in a 2 hour span) in the past month?

**Codebook**

Copy/paste the questions you want to analyze directly from the full codebook into your google doc.   
You need the specific information such as how gender is coded (1/2/9, what is a gender of 9?)  
This will help you from having to hunt through the full codebook when trying to find a specific variable. 


**Data Management, Graphing and R errors Oh My!**

We'll talk about how to identify features of data that will need to be changed prior to analysis. We can't cover them all, nor would you remember them all. This is a place where experience and repetition will be the true learning method. In the meantime, I provide a number of resources to help you identify what to look for. 

You have 2 assignments to turn in this week 1) is your data management RMD code file, the other is a Graphing assignment. Be sure to carefully read the submission instructinos for each. 


### 9/3/18 - [Week 3](https://norcalbiostat.github.io/MATH315/wk/wk03.html)
* You should have been watching and following along with the PDS videos for about a week now. If you are not, do this ASAP or you will fall behind. Think of these as lecture, and in class as practice time. 
* You're going to be refining your research questions this week by conducting a literature review to see what the current state of knowledge is about your project. 
* Then we'll spend some time in the course notes learning how to describe the distribution of data using words, summary statistics and appropriate graphics.
* This is your last chance to get all your R/R Studio bugs resolved. Next week we're hitting the coding ground hard. 

_Note about EC: If you attended a seminar I need some sort of writeup from you to demonstrate that you payed some attention to the statistical or data analysis content of the talk._


### 9/04/18 - [Week 2](https://norcalbiostat.github.io/MATH315/wk/wk02.html) Data entry and import

Office hours (Holt 202) M: 3p-4m, W: 1-2pm, R: 10-11am
(_this weeks Wed hours are cancelled_)

This week we're going to be talking about data, doing some data entry and importing data into R.
You'll start to choose specific variables to address your research questions, create your own team mini-codebook and participate in our first project based assignment that comes with a peer review. 

Two great seminars lined up this week, one in Statistics one in Biology. Both are worth some EC if you attend. They're at the same time, so you can only attend one (obv.) Flyers with details are in Slack. 

Be sure to check the weekly schedule (linked above) for details on how to prepare for the week. 

**Upcoming Assignments**:

* Two (2) DataCamp chapters. This course module is written by the authors of the Open Intro Statistics textbook, the course title in Data Camp is "Data Analysis and Statistical Inference". In the Assignments tab in DataCamp, you will only see the chapter title. 
    - Introduction to R
    - Introduction to data
* Corresponding Blackboard Learn quizzes. _(2 attempts)_
* Problem set 2.2 - Blackboard quiz of 10 randomly selected questions from a pool of questions. _(Unlimited attempts)_
* hw02 - Research codebook assignment (created in Google Drive directly). Will be peer reviewed. 


### 8/27/18 - [Week 1](https://norcalbiostat.github.io/MATH315/wk/wk01.html) Welcome to Fall 18!
* This course website contains all materials except the textbook for this class. Be sure to familiarize yourself with the organization. You will be here a lot. Bookmark this page.
* Specifically click on and explore items in the top navigation bar.  
* Take this survey to help choose when I should hold Office Hours https://goo.gl/forms/qLBv2jMF6fBv3BTR2 
* Check Blackboard for links to the required course materials (also available on the syllabus) 
* Check week 1 for how to successfully prepare for Monday. 



