---
title: "Learning Tools"
output: 
  html_document: 
    toc: yes
    toc_float: true
    css: css/sandstone.css
---

# Learning Journals (LJ)

A Google doc where you will be writing responses and reflections to certain in-class activities.
[Why use a learning Journal?](https://www.teachthought.com/literacy/20-types-of-learning-journals-that-help-students-think/)

-   Date each entry. Write entries in reverse chronological order, from newest at the top to oldest at the bottom.
-   Use 1st level headers for each date so a nice outline is created that helps both of us navigate
-   Here is a [list of writing prompts](metacognition-prompts.html) that you will be going through this semester.

------------------------------------------------------------------------

# Think-Pair-Share (TPS)

These are short periods (1-2 minutes) where you are to

1.  Think about a question or a prompt quietly to yourself first. Write your thoughts down to help organize them.
2.  Pair up with another person and share out what you wrote down or thought about. Actively listen to what they thought about, and notice similarities and differences.
3.  Share your summary with the class as requested.

------------------------------------------------------------------------

# Peer Review (PR)

Most assignments will have a Draft due date.
Then a period of peer review for approx 2 days, where your job is to help your classmate get the best score possible.
This includes helping spot check their code, identifying places that can be removed or fixed, or guidance on how to work out a problem.
After the peer review window has closed, you have another 1-2 days to make corrections and submit your final version.

## Why do we do peer review?

-   Everyone has different thought processes and may have approached the question from a different perspective that can help you learn the material.
-   Co-authoring and reviewing your peers work is part of a professional research position.
-   Learning how to provide good feedback will make you a better collaborator
-   This is a delayed version of paired programming - another set of eyeballs can typically help you find your mistake.
-   I will be looking for different things than your peers will be. This is a good thing. They are looking from “untrained eyes”, which can be very critical to make sure you are explaining yourself clearly. I can better “figure out” what you are meaning to say - they are the ones that will best tell you when/where you need to explain your findings better.

No matter what you end up doing after graduation, the quality of your ideas and work will be judged, in a large measure, by how well you can communicate in writing to diverse audiences.
Participating in peer review can help you learn to shape their written language as a medium of communication with readers.
[[Ref.]](https://teachingcenter.wustl.edu/resources/writing-assignments-feedback/using-peer-review-to-help-students-improve-their-writing/)

## How do I review my peers work?

-   Check the Peer Review Rotation spreadsheet in Google Drive to see who you are scheduled to review.
-   If one of your reviewees did not submit the assignment DM them in Discord first to see if they are just running a little late.
    -   If it’s getting reasonably late then just pick another person to review that doesn’t have a lot of comments so far and DM me to let me know.
-   By using comment bubbles, provide feedback to your peers.
-   Be specific. Give the type of feedback that you want to receive.
-   Minimum four corrections or suggestions for improvement.

## Giving good feedback

-   Compliment the author. What did you like about their writing or plots?
-   Make specific suggestions regarding things like word choices, use of details, organization, topic
-   Mark corrections such as spelling, grammar, punctuation, analysis methods, coding errors, but don’t try to turn their paper or style into your style.
-   If you find a claim that is not supported by data in the document (or cited) be sure to point it out.
-   Check their work against what is required. Do they have all required elements?

## Grading of peer reviews

As I do my reviews on the same document, I will be reading and assessing your peer review.
If I find your review is not providing quality feedback to the author you will not receive credit for that review.
You may see the cells in the peer review spreadsheet changing color as I check off your review.

[ If you consistently do not turn in a draft that is complete enough for a review, or consistently provide sub-par reviews to your classmates, I reserve the right to stop assigning you work to review and stop having your work reviewed. You will not have the ability to make up these points. ]{style="color:red"}

------------------------------------------------------------------------

# Quizzes (Qz)

Quizzes are a great way to test yourself, enhance recall, and self-assess your comprehension of the subject.
Questions come from the textbook, Applied Stats Course Notes, and in-class discussion.
Quizzes are administered in Google Forms, and done in two parts.
Expect 10-20 questions each time.

1.  **Individual**: First try to answer as many questions without looking at your notes.
    Then use your notes to answer the rest.

2.  **Group**: After the individual quiz closes I will choose 1-4 questions that scored the lowest.
    We will do a class-wide discussion of those topics, then you will work in groups to redo the selected questions for half credit.

------------------------------------------------------------------------

# 3-2-1 Bridge (Bridge)

This activity is designed for you to visualize and reflect on how your thinking and perceptions on a specific topic change throughout a module, or course.
This routine invites learners to uncover their initial thoughts, ideas, questions, and understandings about a topic, and then, after engaging in learning experiences and experiencing some instruction, to connect these to new thinking and ideas

You will complete this work in your Learning Journal.

You will be given a prompt and asked to record your thoughts about it in three phases.
**Do not overthink your responses!**

Freely brainstorm your initial thoughts, there is truly no right or wrong response.

Title and date your entry.
We will be coming back to these entries to complete the "bridge" after you learn some more about this topic.

## Start the Bridge

#### Phase 1: Record 3 words

Quickly write three words that come to mind when you think of the prompt.

#### Phase 2: Ask 2 questions

Write two questions that you were wondering about when thinking about the prompt.

#### Phase 3: Develop an analogy or metaphor

Write an analogy or metaphor that encapsulates your ideas about this prompt

**Analogy**: *a comparison between two things, typically for the purpose of explanation or clarification.* \* a thing which is comparable to something else in significant respects.
Examples include:

> -   "works of art were seen as an analogy for works of nature"
> -   "as light as a feather" \*"As quiet as a mouse"

**Metaphor**: *a figure of speech in which a word or phrase is applied to an object or action to which it is not literally applicable* \* a thing regarded as representative or symbolic of something else, especially something abstract.
Examples include:

> -   "The amounts of money being lost by the company were enough to make it a metaphor for an industry that was teetering"
> -   "She is doing a tightrope walk with her grades this semester."

## Return to your Bridge

> Focus is on *comparing prior understanding to current thinking*

#### 3 words

-   Review your prior entries for 3 words.
-   What 3 words come to mind now?
-   Write down why they have, or have not changed? It could be a change from the beginning, of the midterm of the semester.

#### 2 questions

-   Review your prior set of questions.
-   Have they been answered yet? You don't need to write down the answer, just state if they have been answered.
-   Write down any new questions that has arisen.

## Complete the Bridge

> Focus is on *comparing prior understanding to current thinking* AND *realizing changes in thoughts across the semseter*

#### 3 words

-   Review your prior entries for 3 words.
-   What 3 words come to mind now?
-   Write down why they have, or have not changed? It could be a change from the beginning, of the midterm of the semester.

#### 2 questions

-   Review your prior set of questions.
-   Have they been answered yet? You don't need to write down the answer, just state if they have been answered.
-   Write down any new questions that has arisen.

#### 1 metaphor/analogy

-   Review your initial analogy.
-   Do you need to revise it to reflect your current thinking about the prompt now?
-   What has or has not changed?

------------------------------------------------------------------------

# Exam Error Assessment

For the midterm you will have an opportunity assess your errors on the midterm, make corrections, review the corrections with me, for a partial return of the credit lost.
[Error Assessment Form](notes/Analyzing%20exam%20errors.pdf)

-   Download the error assessment form.
-   Review page 3, six types of test taking errors.
-   Fill out page 2 by using the commenting/editing tool in Adobe to add text.
-   Redo the problems you got wrong on a separate form.
-   Make an appt with me to go over your corrected answers. **You must have your error assessment form filled out before you meet with me.**
