---
title: "Module Schedule"
execute: 
  eval: false
---

Schedule goes here

```{r}
library(tidyverse)
library(gt)
# Import data & create new variables
mod <- googlesheets4::read_sheet("1JyPeMAAHb3yrCzxDpnWqB7k-KsCTkULIPILAAsfai78", 
                                 sheet="module_overview") 

# content rows
content  <- mod %>% filter(is.na(tnum))

# which rows have topic numbers 
tn <- mod %>% filter(!is.na(tnum)) %>% 
        select(tnum, Topic) %>%
        mutate(start=0, end=0)

for(t in 1:max(tn$tnum)){
  tn$start[t] <- min(which(floor(content$Order)==t))
  tn$end[t]   <- max(which(floor(content$Order)==t))
}

out <- content %>%
  # wrangle hw links
  separate(col=Do, into=c("hw.name", "hw.link", "hw.due"), sep="-| ") %>%
  mutate(Date = format(Date,"%m/%d"),
         hw.due = gsub("(", "<b> \r\n Due (", hw.due, fixed=TRUE), 
         hw.due = gsub(")", ")</b>" , hw.due, fixed=TRUE),
         hw.sol = ifelse(!is.na(sol), sol, ""), 
         Do = ifelse(!is.na(hw.name), 
                     paste0(sprintf("[%s](%s)", hw.name, hw.link), 
                            "<br>", hw.due, "<br>", hw.sol), 
                     NA), 
         Notes = ifelse(!is.na(Notes),Notes, NA)) %>%
  select(Date, Topic, Notes, Read, Watch, Practice = Do, Assess=quiz) 


# highlight rows
wk.labs <-  "background-color: #bb9457; color: #fff;"
hlt.wks <-  "background-color: #6f1d1b; color: #fff;"
```

```{r, results='asis'}
out %>% 
  kable(align="cllllcc", escape=FALSE) %>% 
  kable_styling(bootstrap_options = c("hover", "striped", "responsive", "bordered")) %>% 
  pack_rows(tn$Topic[1], tn$start[1],   tn$end[1], label_row_css =wk.labs) %>% 
  pack_rows(tn$Topic[2], tn$start[2],   tn$end[2], label_row_css =wk.labs) %>%
  pack_rows(tn$Topic[3], tn$start[3],   tn$end[3], label_row_css =hlt.wks) %>%
  pack_rows(tn$Topic[4], tn$start[4],   tn$end[4], label_row_css =wk.labs) %>%
  pack_rows(tn$Topic[5], tn$start[5],   tn$end[5], label_row_css =wk.labs) %>%
  pack_rows(tn$Topic[6], tn$start[6],   tn$end[6], label_row_css =hlt.wks) %>%
  pack_rows(tn$Topic[7], tn$start[7],   tn$end[7], label_row_css =wk.labs) %>%
  pack_rows(tn$Topic[8], tn$start[8],   tn$end[8], label_row_css =wk.labs) %>%
  pack_rows(tn$Topic[9], tn$start[9],   tn$end[9], label_row_css =hlt.wks) %>%
  column_spec(1, width = "5%") %>% 
  column_spec(2, width = "22%") %>%
  column_spec(3, width = "15%") %>%
  column_spec(4, width = "3%") %>% 
  column_spec(5, width = "25%") %>%
  column_spec(6, width = "15%") %>%
  column_spec(7, width = "15%")
```


