---
title: "Research Project"
output:
  html_document:
    toc: yes
    toc_float: yes
---

## Overview

Throughout the entire semester you will work with a partner to analyze a data set and present your research findings as a poster during finals week. Your assignments will serve as a first draft of exploration into your research questions, and helps you build your story. 

You will build up your project in stages, revising multiple times. The end goal is a research poster that you will present during finals week. You will be summarizing your findings using Google Slides. This will help you concisely explain your research topic and findings in a way will be easier to translate (fit) onto a poster. Here is the general outline, with each stage is explained in detail further below. 

* Stage 1: Choose a data set and identify a few research topics
* Stage 2: Introduce your project and variables of interest
* Stage 3: Explore your data and relationships
* Stage 4: Analyze bivariate relationships
* Stage 5: Multivariable modeling & summarizing findings
* Stage 6: Poster Creation & Presentation


### Peer Review

Stages 2-6 are subject to peer review. See the [Peer review](learning_tools#Peer_Review_(PR)) section of the Learning Tools page for details.

Once you have addressed a particular piece of feedback mark it as "resolved" in Google Slides. 

⚠️ *Do Not Delete Feedback until notified that it is okay*


### General Notes

* At each reviewed stage you should update anything you need to change based on feedback, such as correctly making graphics, writing results correctly etc. 
* The contents of each slide are specified in the slide template and explained below.
    - You are welcome to have "staging" slides where you can dump content, thoughts, analyses that you _may_ end up using. **These extra slides should be at the END of the required slides.**
* There are also [example slides](https://drive.google.com/drive/folders/1Aaa4Zkn0OHmYu1e_8jJBJ39w-DEdbjSb) from prior students as a references. (Note the template may have been updated since then.)



## Stage 1: Choose a data set and identify a few research topics

* Project data you can choose from can be found in this [Google Drive folder](https://drive.google.com/drive/u/0/folders/1jULudBjRbHdW-uLIvmMbxRBEJJkq9crY). 
* Browse through the available data sets, read the summaries and skim the codebooks.
* Add your names to [Proposed Research Topics](https://docs.google.com/spreadsheets/d/1dNTr0SKnwoT3XBHJY6cGh3fEeJCfxlDmYAUZ10uX89w) once you have chosen a topic.
    - Some data sets are limited to only 1 or a few analysis pairs working on the same data set. Those have set rows, do not add more rows. 
    - If your chosen data is not listed, add a row for it. 
* Download the codebook to your class folder. 
* You will work through writing out a few research questions as part of Homework 02. 


<a href="#otherdata" data-toggle="collapse">**Consideration of other data sources** (click to expand)</a>
<div id="otherdata" class="collapse">

Under only very strict certain circumstances I will allow for other data sets to be used (this includes your senior thesis data). You must make an appointment to meet with me to go over your data, codebook and research question for this to be a consideration.

**Criteria for proposing new data sets**

* File type must be a .txt, .csv, .xlsx or .xls file
* File size is less than 1 Gig 
* A codebook or data dictionary that fully explains what each variable means is available.
* There are at least 200 rows (observations), but ideally between 500-1000. 
* There are 20 or more variables 
    * At least 4 quantitative variables
    * At least 1 categorical variable 

</div>

<br>

## Stage 2: Introduce your research question and variables of interest

* Make a copy of the Project Template found in the `00 Poster Prep` folder in our Google Drive. 
* Name your file using your team's first names only (e.g. `robin_katie`)

These slides for this stage are pale yellow in the template. 

* **Slide 01**. Title 
* **Slide 02**. Introduction 
* **Slide 03**. Background & lit review. 
* **Slide 04**. Explain the research problem / topic area
* **Slide 05**. State your Research Question as a testable hypothesis. 
* **Slide 06**. Introduce the data. Where does it come from, how was it collected. How many records? 
* **Slide 07**. Description of measures (variables) being used. 



⚠️ **Pay attention to slide Numbers!**

* Please ensure that all content is on the slide as expected. 
* Slides will not be filled in in direct numerical order.
* Check the template if you are confused. I have added slide background coloring to help you keep you on track



## Stage 3: Exploratory data analysis 

These slides are pale blue in the template. 
   
* **Slide 09**. Fully describe your primary response variable
* **Slide 10**. Fully describe your primary explanatory variable
* **Slide 11**. Fully describe the relationship between your primary explanatory and primary response variables
* **Slide 13**. Fully describe the relationship of a third variable to either your explanatory or response variables

All using appropriate summary statistics, graphic and an explanatory sentence. 


## Stage 4: Bivariate Inference 

These slides are pale purple in the template. 

* **Slide 08**. Describe in a few sentences what analysis tools you will use to answer your research question
* **Slide 12**. Analyze the relationship discussed in slides 11
* **Slide 14**. Analyze the relationship discussed in slides 13

This should be a conclusion written in English, in the context of the problem, includes summary statistics, confidence interval and a p-value. 


## Stage 5: Multivariable modeling & summarizing findings

You are trying to understand the relationship between your explanatory and response variable, in presence of information contained in other variables. 

These slides are pale green in the template. 

**Slide 15: Model Building**

* Build a multivariable model by adding additional predictors to the model. 
* Explain your model building process in a few bullet points. 
  - What variables did you test as other explanatory variables? 
  - How did you determine your final model? 
* Include any variables that were found to be significantly associated with the outcome
* If you have a confounding variable, you still need to keep your primary explanatory variable in the model. 

**Slide 16: Multivariable Model - Summary of results**

* A table or plot of the regression coefficients (or Odds Ratios) must be presented. 
* At least one coefficient, the primary explanatory variable, must be interpreted in context of the problem. 

**Slide 17. Model Assessment**

* If using a linear or log-linear model; 
    - present and interpret the model diagnostic plots
    - report and interpret $R^{2}$
* If using a logistic regression model; 
    - report the results of a test for goodness of fit
    - report and interpret the model accuracy, and the cutpoint used. ([Ref: ASCN Ch 12.5](https://norcalbiostat.github.io/AppliedStatistics_notes/model-performance.html))

**Slide 18. Discussion**

* Here you will explain what your graphical and inferential results tell you about your topic.
* Discuss if your research hypothesis was supported, if it was not, why you think that might be
* Explain the overall story/trend/what you learned when you consider your univariate, bivariate & multivariate results about your topic.
* Compare your results to previous research results. Do they agree or disagree? 

**Slide 19. Implications**

* What are the practical implications of your results?
* What could others do with your findings? 
* What future research needs to be conducted?
    - This needs to be more specific than "other variables could be explored". Which variables and why? What other research articles indicate that those other variables are relevant? 

**Slide 20. Limitations**

* Who are the results of this study generalizable to? (i.e. a subset of individuals?)
* Were there any model assumptions that were not upheld? 
* If this is an observational study, you should make a statement about the findings are associations and not causal in nature
* Are there other factors that could explain your response variable that you did not include in your model? 


**Slide 21. References**  

* You can use smaller font to get all references on one slide.
* Use references from research plan, and any additional references gathered along the way. 
* Make sure these are correctly done in APA format.
* Proper citations for 
    - [Add Health](http://www.cpc.unc.edu/projects/addhealth/faqs/addhealth#how-do-i-cite-the-add-health-contractual-data-)
    - *R*: Type `citation()`
    - [R Studio](https://support.rstudio.com/hc/en-us/articles/206212048-Citing-RStudio)
    - [SPSS](http://www-01.ibm.com/support/docview.wss?uid=swg21476197)
    - [How to cite software in Text](http://blog.apastyle.org/apastyle/2015/01/how-to-cite-software-in-apa-style.html)
    

## Stage 6: Posters Presentations

* During our scheduled finals time, analysis teams will present their research posters in a poster symposium setting. Half the teams will be up at a time. When not presenting, you will be scoring your peer's class's posters using [this scoring sheet](https://forms.gle/SWBM96MjcEmMDHGo9)
* Posters can be in powerpoint (the standard format for research posters), or Google Slides (once appropriately sized)
    - Regardless of the file type, you must use a template. Do not try to reinvent the wheel. 

### Poster Guidelines

See the full guidelines [in this blog post](https://www.norcalbiostat.com/post/2022-11-26-poster-guidelines/). This post includes: 

* [Links to poster templates](https://www.norcalbiostat.com/post/2022-11-26-poster-guidelines/#templates)
* [Details on what each section should contain](https://www.norcalbiostat.com/post/2022-11-26-poster-guidelines/#content)
* Guidance on [aesthetics](https://www.norcalbiostat.com/post/2022-11-26-poster-guidelines/#aesthetics) and [printing](https://www.norcalbiostat.com/post/2022-11-26-poster-guidelines/#printing)
* [Examples of professional and prior student work.](https://www.norcalbiostat.com/post/2022-11-26-poster-guidelines/#examples)


### Draft version

* This draft is graded on a 1-10 scale on how complete the poster is. You should consider this a draft that you would circulate to your colleagues for final review and comments. 
    - Basically the more work I think you need to put into your poster to make it presentable, the lower the points you get for the draft. 
* Use the [evaluation criteria](https://www.norcalbiostat.com/post/2022-11-26-poster-guidelines/#evaluation-criteria) as a guide for what I am looking for.


**Submission and Peer Review Instructions**

* Save your poster as a PDF and upload to the `Google Drive/Project Poster Drafts` folder. 
* To conduct your peer review, open the PDF from Google Drive directly in your browser. 
    - Use the comment feature to write the comments directly into the poster file itself. 
    - provide at least two specific comments for each
        - something that can be improved
        - something that is good
    

### Final Version

* Upload your final poster (as printed) to the `Google Drive/Project Poster Final Version` folder. 
    - PDF preferred. PPTX ok.
* Scoring will be done via [Google Forms](https://forms.gle/oFMQ2hqtthZFPq7T7). It looks exactly like the [evaluation criteria](https://norcalbiostat.netlify.com/lec/poster_guidelines/#evaluation-criteria).
    - When not presenting, you will walk around and learn about others research. Ask them questions, fill out the evaluation on your phone as you go. Printed copies will be available upon request so you can submit later. 
* The final grade will be determined by
    - Base score = **30%** student score + **70%** instructor score **+ bonus pts** for best in show awards. 

----

## Grading Method

Instead of assigning specific points to each stage and adding up the points for an overall score, this work will be done through a series of revisions gaining feedback from both your peers and the instructor at each stage. 

* For each slide to be assessed you will be marked as either "needing revision", "meeting expectation", or "exemplary".
* I will update your status column for the slides that are being assessed at that stage. 
    - I will also check on any prior slides that are at 'needs revision' stage. 
* You can request a reassessment of prior work at (nearly) any time. (You can ask for it, I just may not get to it until the next time I'm reviewing slides.)
* **You are responsible for keeping track of your status!** Suggestion - use conditional formatting on column F in your sheet. This is the color scheme I use:
    - Go to "Format --> Conditional Formatting"
    - Single color, apply to range F2:F22
    - Format cells if 
        * `Text contains Not Assessible` (Red)
        * `Text contains ME` (light green)
        * `Text is exactly E` (dark green)
        * `Text contains NR` (yellow)



### Rubric

This is a method of 'ungrading' that I have been wanting to try for a while. At the math congress (camping conference) I attended the first week of October a math educator discussed this method with us and so I was inspired to finally test it out. This project is a perfect opportunity to do so. 

This means that the Assessment item descriptions are a work in progress. Right now they are slightly modified from the old grading rubric. I may add, combine, or reword items as I do my revisions to better fit what I am actually looking for. 

Each person has their own 'project assessment' Google spreadsheet (same location as your poster) that shows you what achievement stage you are at for each item. It is locked to only view mode and only you and I have access to it. 


### ... but points!??

In the end this still has to be converted to a point value/letter grade right? So here's how I'm going to do it. The poster prep slides make up 80 out of the 110 points for the project. 

* If you have $\geq$ 90% of assessment items at 'exemplary' and none at 'needs revision', that's "A" work and you get the full 80 pts. 
* If you have $\geq$ 90% of assessment items at 'meets expectation' and no more than 1 at 'needs revision', that's "B" work and you get 72 pts. Note 'meeting expectation' does not correspond to _A_ level work
* If you have $\geq$ 80% of assessment items at 'meets expectation' and no more than 2 at 'needs revision', that's "C" work and you get 64 pts. 

