---
title: "Syllabus for Applied Statistical Methods I"
author: "Dr. Robin Donatello"
date: "MATH 315-01 & -02, Spring 2019"
output: pdf_document
geometry: margin=0.75in
urlcolor: blue
---


> "Statistics in the service of research"

This course introduces you to modern statistical data analysis techniques so that you can make data-informed decisions. At the end of the semester you will present your research findings in a poster presentation format to your peers. 

In this project-based course, you will have the opportunity to answer questions that you feel passionately about through independent research based on existing data. The course offers a lot of one-on-one support, directed opportunities to work with other students, and training in the skills required to complete a project of your own design. We will use collaborative tools and software that are common in many workplaces and research labs. These skills will prepare you for many different career types. 



## Logistics

* **Instructor:** Dr. Robin Donatello  
* **Office Location:** Holt 202  
* **Phone Number:** 898-5767  
* **E-mail:** rdonatello@csuchico.edu 
* **website:** http://norcalbiostat.github.io/MATH315/ 
* **Slack Channel:** http://math315-s19.slack.com 
* **Prerequisites:** Basic computer literacy. Recent statistics course such as Math 105. Math 130 is recommended. 
* **Meeting Days and Times:**  Sec01: TR 12:30-1:45, Sec02: MWF 9-10am, HOLT 171
* **Office Hours:** Holt 202: TBD (See website for confirmed times)


Best method of contact? Slack! (Then email.)

You can download the Syllabus in PDF form by clicking [this link](syllabus_315_s19.pdf).


## Additional Support

* The Data Science Initiative offers year-round training workshops and seminars on data-science related topics including R. See http://datascience.csuchico.edu for more information and a schedule of events.  
* Community Coding: TR 2-4pm, THMA 116 [[flyer]](cc_flyer_s19.pdf)
    - Students, staff, faculty, and the public are invited to join our Community Coding sessions. Bring your computer, coding projects, and your questions to this open working environment. 
    - Commit to studying 1 hr. per week for your (not necessarily CS) programming course and earn credit. Enroll in MATH 290-02 (5854), a 1 unit credit/no-credit course.  Credit is earned by attending at least 10 times.



### Learning Outcomes

By the end of the semester students will be able to 

* Develop a testable research question. 
* Create and understand how to use a codebook to identify data relevant to that question. 
* Process, screen, recode, transform, and clean data.
* Describe data using visualizations and words. 
* Select and carry out an appropriate statistical analysis.
* Explain study results and limitations to a non-technical audience. 
* Understand and implement a reproducible research pipeline. 
* Become a data nerd (Optional, but recommended).



## Required Materials (the "stuff")

* **Lecture Videos:** This course uses lecture videos from a program called Passion Driven Statistics. These are essential part of your learning materials. Plan to bring headphones in case you need to watch these during class. 
* **Course Notes**: Purchase from Chico Packet Pro for ~$25. Hours and locations in Blackboard. 
    - You will write directly into this inside and outside of class. 
    - A color PDF version available as supplementary material on the course website. 
* **Reliable Laptop with internet connectivity**: Required to bring every day. Contact me if this poses a problem or concern for you. 
* **Computer Software:** We will be using R Studio in the cloud. A working platform has been nearly fully setup for you. You are welcome to install these programs on your laptop if you choose. Help is available for this setup. 
* **Open Intro Statistics textbook** https://www.openintro.org/stat/textbook.php?stat_book=os. 
    - Optional, but very very highly recommended. 
    - A very good resource for digging deeper into topics or simply having another method of explanation and demonstration.
    - Free PDF or $15 hard copy

  
### Online platforms

* **Course Website:** Everything! Schedule, syllabus, videos, notes, readings, homework etc. 
* **Blackboard Learn Use:** Grades, due dates, and quizzes. 
* **Google Drive** Surveys, data collection, quizzes, written assignment submission, peer review and assignment feedback. 
* **Required Accounts** 
    - R Studio cloud. Use the link in Blackboard to join our workspace. 
    - Slack: An asynchronous discussion platform with a lot of collaborative functionality. 
        - Workspace URL: http://math315-s19.slack.com. Use the link in Blackboard to join our workspace. 
        - Download either the desktop app or the phone app. 
        - This is where I will make announcements and share assignment files as needed. 
        - All coding questions must go here. 
    - Data Camp: An invitation to join will be sent to your campus email before the semester starts. 
        - If you already have a DataCamp account it should automtically add you to the new classroom and your work will transfer over. 

## Class Format (how do we use that stuff?)

You've heard of a "flipped classroom" before right? Well this is kinda that. This course provides a series of lessons and assignments aimed at preparing students conceptually and technically for the various steps taken in completing their research project. You are expected to make marked progress each week and to come to class prepared with questions and planned next steps. It is important to note that to really learn the material and skills presented in this course, you will need to devote a substantial amount of out of class time working on this class.

### Before class
* Watch the videos and complete the DataCamp modules where assigned. 
* Read through the course packet and fill in the blanks
* Take the corresponding quiz (1-2/week). 

### During class
* We will briefly review the topic for the day
* Go over any quiz questions that were very low scoring
* Then it's your turn to work on your research project with the support of me and peer mentors. 
* Work with others, seek additional support and clarification, and provide and receive help from peers.


This class is an implementation of a program called "Passion Driven Statistics" developed at Wesleyan university and dissemenated nationwide as part of a NSF Grant. You can learn more about this program here: https://passiondrivenstatistics.com/. As a student in this class, you will be contacted by Lisa Dierker at Wesleyan to participate in a pre- and post-course survey. If you choose not to participate it will not affect your grade but I will give a few extra points towards participation if you choose to respond. Your input in assessing this program is is valued. 

## Mututal Expectations

I am a very personable individual who likes to get to know my students as well as let the students get to know me. I am a fair instructor, but I realize that not everyone digs my teaching style. In full acknowledgement of this I provide as many resources for success as possible; therefore, success in this course is accomplishable if you do your part. The quizzes, assignments, and project are a challenge, therefore, ample time preparing is necessary. 

The peer mentors and I are here for you, but you have to use your voice and speak with me about any concerns you may have. The best way to contact me is through Slack, or email. To keep students informed about the course I send out weekly updates through Slack. 

It's important to note that this Spring I will be teaching 2 sections of the same course on ENTIRELY different schedules (MWF & TR). So I am going to forget who I told what too, I will strive to keep due dates separate but I expect to mess up at least once. I will do my best to be as organized as possible to make things smooth for you. I need you to understand that I am only human (omg!), and to have patience and understanding with me. Broken links on the website? Mixed up dates in blackboard? Tell me so I can fix it! 

\newpage

## Coursework Specifics (what are you graded on?)

1. **Participation**: Daily attendance is mandatory unless you talk to me ahead of time. You cannot take advantage of the learning time if you are not present. Each day I will mark attendance early on during the class session. I start promptly and late arrivals are very disruptive. To receive credit for the day you must do TWO things. 
    - You must attend class for the entire class. 
    - You must actively participate in class by answering questions, contributing to discussion, asking questions, paying attention, and participating in activities
    - 3-5 days absent 10% penalty, 5-10 days absent 50% penalty, 10+ days absent earns no credit. 


2. **Community & Learning**: These activities are designed to foster learning and peer collaboration in and outside the classroom. 
    - You will be conducting peer reviews for all project assignment throughout the semester. 
    - Being a contributing member in our Slack community. Ask and answer questions. Share code and ideas. Share silly math jokes and interesting articles. 
    - You also must attend at least one community coding session, and visit me once in my office during the semester. 
        
3. **Quizzes (1-2 per week)**
    * **Quizzes** Designed to ensure you are prepared for class and to help me learn what topics need clarification. 
        - Administered online through Google Forms and to be completed prior to class individually. 
        - Group quizzes's will occur at the beginning of class to clarify and discuss commonly missed questions. 
    * **Data Camp (DC) quizzes**: We will use Data Camp as a way to work on learning R outside of class. 
        - There will be a corresponding BBLearn learn quiz associated with each lesson. 
        - You will have multiple (but not unlimited) attempts at these quizzes. 
        - Questions can be conceptual, interpreting results, and asking you to write code to demonstrate a task that was   covered in the lesson. 

4. **Written HW**: Written assignments are methods to demonstrate you can apply the material that you learned to a new problem.
      - Assignments will build to the completion of a project that will be presented at the end of the semester as a poster. 

7. **Exams:** There will one midterm and one final exam. 
    - An Error Analysis can be conducted on the midterm to earn back up to half the credit missed. 
    - This is where you get back your exam, fix your mistakes, and explain your corrections verbally to either me or a tutor. 
    
8. **Project:** You will be working in pairs on a project throughout the term. 
    - Written assignments throughout the semester are specifically geared towards progressing your analysis project. 
    - You will present your work as a poster at the end of the semester. 
    - You will have two opportunities to provide feedback and critique of your research partner to ensure the contributions to work do not become imbalanced. 
    - **I reserve the right to adjust your grade up or down based on your peer evals and my observations of your engagement in the project.
  

## Grading

* Your final grade will almost be a straight sum of points earned and will be displayed as a running total in Blackboard Learn.  (Almost, because I will drop the lowest 25% of your individual quiz scores)
* The approximate contributions per category are:   
    - Participation 10%
    - Community and learning 10%
    - Quizzes 15\%
    - Written Assignments 15\%
    - Exams 20\%
    - Project 30\%
* I use a standard grade cutoff of 100-90\%: A, 89-80\%: B, 79-70\%: C, 69-60\%: D, 0-59\%: F Plusses and minuses will be as displayed on Blackboard Learn. 

# Topic Overview
A detailed schedule can be found on the course website. 

* Data Collection and recording
* Preparing data for analysis
* Data Visualization
* Foundations for Inference: Random variables, Parameters vs. Statistic, Confidence Intervals, Hypothesis Testing
* Inference for a single sample (t-tests, $\chi^{2}$ tests)
* Inference comparing multiple samples (t-tests, ANOVA, $\chi^{2}$ tests)
* Linear regression analysis
* Logistic Regression analysis
* Multivariable Model Building (moderators, interactions, categorical predictors, model fit)


----

# Policies

## Late Assignments

All assignments are to be completed upon the due date as announced by the instructor. All assignments that are turned in after the deadline has passed will receive NO CREDIT, however, students will receive feedback. No exceptions will be made. In cases of emergency, please contact your instructor immediately.

## Academic Integrity

Academic integrity is defined as "a commitment, even in the face of adversity, to five fundamental values: honesty, trust, fairness, respect, and responsibility". From these values flow principles of behavior that enable academic communities to translate ideals to action. Academic integrity is expected and required. No forms of cheating or plagiarism will be tolerated. Please see your student handbook at https://www.csuchico.edu/scrr/integrity.shtml if you have questions about the meaning of these terms or the consequences of violating academic integrity. 

## Scientific Integrity

The rules of science should be carefully upheld in everything that you do. The following behavior is absolutely unacceptable: Data fabrication, selective reporting, omission, suppression or distortion. Please be mindful that there is no such thing as a "little scientific misdemeanor." 


## Plagiarism

Using someone else's words or ideas without properly citing them is plagiarism. The CSU academic integrity policy distinguishes between misuse of sources and intentional plagiarism. If a student makes an attempt to "identify and credit his or her source, but does so improperly, he or she will not be penalized according to our policy.
However, students should make every effort to learn the proper format for correctly citing sources, since this is an essential aspect of academic work.

Intentional plagiarism occurs when the student "deliberately uses someone else's language, ideas, or other original (not common knowledge) material without acknowledging its source"" and in so doing represents them as his or her own. This includes borrowing another's phrases or sentences without using quotation marks or citations; cutting and pasting whole paragraphs (or papers) from websites without acknowledgement; or borrowing ideas from someone without citing them.


## Adding and Dropping the course

The last day to add or drop classes without special permission by the instructor is 2/1/19. No adds or drops are allowed after 2/15/19 without a serious and compelling reason approved by the instructor, department chair, and college dean.


## Americans with Disabilities Act

If you need course adaptations or accommodations because of a disability or chronic illness,  or if you need to make special arrangements in case the building must be evacuated, please make an appointment with me as soon as possible, or see me during office hours. Please also contact Accessibility Resource Center (ARC) as they are the designated department responsible for approving and coordinating reasonable accommodations and services for students with disabilities. ARC will help you understand your rights and responsibilities under the Americans with Disabilities Act and provide you further assistance with requesting and arranging accommodations.

Accessibility Resource Center  
530-898-5959   
Student Services Center 170  
arcdept@csuchico.edu  


## Chico State Basic Needs Project

The **Hungry Wildcat Food Pantry** provides supplemental food, fresh produce, CalFresh application assistance and basic needs referral services for students experiencing food and housing insecurity.

All students are welcomed to visit the Pantry located in the Student Service Center 196, open Monday-Friday, 11am-4pm or call 530-898-4098. 

Please visit the Chico State Basic Needs website http://www.csuchico.edu/basic-needs for more information.

 
-----

_Last updated: `r format(Sys.time(), "%a %b %d %Y %X")`_

