---
title: "3-2-1 Bridge Instructions"
output:
  html_document:
    theme: sandstone
    highlight: tango
    css: ../css/sandstone.css
  pdf_document: default
---

# Purpose
This routine invites learners to uncover their initial thoughts, ideas, questions, and
understandings about a topic, and then, after engaging in learning experiences and
experiencing some instruction, to connect these to new thinking and ideas

You will complete this work in a "Learning Journal". This can be on paper or electronic. 

You will be given a prompt and asked to record your thoughts about it in three phases.

> Do not overthink your responses!

Freely brainstorm your initial thoughts, there is truly no right or wrong response. 

---

### Phase 1: Record 3 words
Quickly write three words that come to mind when you think of the prompt. 

### Phase 2: Ask 2 questions
Write two questions that you were wondering about when thinking about the prompt. 

### Phase 3: Develop an analogy or metaphor
Write an analogy or metaphor that encapsulates your ideas about this prompt

* **Analogy**: _a comparison between two things, typically for the purpose of explanation or clarification._
    - a thing which is comparable to something else in significant respects.
    - Ex: "works of art were seen as an analogy for works of nature"
* **Metaphor**: _a figure of speech in which a word or phrase is applied to an object or action to which it is not literally applicable_
    - a thing regarded as representative or symbolic of something else, especially something abstract.
    - Ex: "the amounts of money being lost by the company were enough to make it a metaphor for an industry 
      that was teetering"


## Title and date  your entry
We will be coming back to these entries to complete the "bridge" after you learn some more about this topic. 



