---
title: 'HW 01: Team Formation & Self Regulated Learning'
author: "Course Number - STUDENT NAME"
date: "Date"
output:
  html_document:
    theme: readable
    highlight: tango
    toc: yes
    toc_float: yes
  pdf_document: default
---

# Instructions

1. Download the Rmarkdown [[Rmd]](hw01_intro_template.Rmd) template file to use for this assignment. 
2. Replace `template` in the file name with your userid (i.e. `hw01_introductions_rdonatello`). 
3. Replace the course number with section, your name and date in the YAML header. 
4. You will compile this document to a PDF format and submit to Blackboard learn by the due date. 
    - You must have LaTeX installed to compile to PDF. 

This is an individual assignment. 

# Part I: Team Formation

The [University of Minnesota](http://teamwork.umn.edu/) has a fantastic website devoted to surviving group projects.
You will have a group for immediate support in this class, but the project will be done in pairs. 
I highly recommend you use this site as a resource for not just this, but other classes. 

### Team Roster.
Using the numbered list below, write the name of each team member and one interesting fact or tidbit you learned about them this week. Indicate who will be working together on the project. 

1.
2. 
3. 
4. 

### Team Identity

Now pick a name for your team! Be as creative as you want, but do something other than
"Team 1" or "Group ABC". 

**From henceforth this gathering of people shall be called:** 

\newpage

# Part II: Self Regulated Learning

From the [articles](http://www.norcalbiostat.com/articles/articles.html) page, download and read the "Learning (Your First Job)" article. 

* Answer at least _4_ of the following questions in this document. 


1. **What was the most important insight you gained from the reading? **


2. **What surprised you most in the reading?**


3. **What did you already know?**


4. **Have you been taught how to learn before?  Where?  What did you learn about learning?**


5. **What will you do differently during a lecture, if anything, given what you read?**


6. **How will you prepare differently for exams, given what you read?**


7. **Can you think of other good learning practices that the reading didn't mention?**

\newpage

# PART III: Analysis Data Set

**State what sections and what data set you are interested in learning more about**

