---
title: "HW 01- Orientation to the class, self regulated learning and research team formation"
output:
  html_document:
    theme: sandstone
    highlight: tango
    toc: yes
    toc_float: yes
    css: ../css/sandstone.css
  pdf_document: default
---

# Assignment Overview
The purpose of this assignment is to get you connected with R Studio in the cloud, to do a little self reflection and examination of your learning habits, and to get to know the members of your class and support group. 
 

# Instructions
The specific details for each step are described below. 

* This is an individual assignment
* You will answer the questions directly in the Rmarkdown template file provided in R Studio Cloud. See part I below to get access to this document. 
* When you are done, spellcheck your work using the spellcheck button in R Studio (2 icons to the left of Knit). 
* Knit the final document. When it opens, click the download icon in the upper right corner. 
* Rename this file `hw01_username` i.e. `hw01_donatello.pdf` 
* Upload this file to Google Drive in the **01 Orientation** folder for your section. 


# Part I: Getting Started with online tools

## Slack
1. Go to http://math315-s19.slack.com and make an account to join our workspace. 
2. Download either the desktop app or the phone app. 
3. Post an introduction to yourself in the #introductions channel. Tell us a little about you! Year, major, hometown, any extracurricular activities, one thing you are hoping to get out of this class, and one concern you have about this class. Oh.. and of course any mention of pets should include a photo!
        
## Data Camp
An invitation to join DataCamp will be sent to your campus email before the semester starts. If you already have a DataCamp account email me to let me know and I will manually add you to our classroom. _You must be added to our classroom to get credit_. 

1. Log in to DataCamp and complete the "Working with R Studio IDE" lesson. 

## R Studio in the cloud.
1. Watch this very short tutorial on R Markdown. This is what you will be using to write all assignments in. http://rmarkdown.rstudio.com/lesson-1.html
2. Log into R Studio cloud, and click on our class workspace. 
3. Click on the `stats_project`. This will create a copy the R project into your own workspace. 
    - An "R project" is a pre-configured R environment along with a collection of files. 
4. In the lower right corner click the `hw01_orientation_template.Rmd` to open this R Markdown file. 
5. Replace your name and date in the header section. 
    - Don't delete the quotation marks. 
6. Complete the rest of the assignment below by writing the answers directly in the template. 
7. To see what the final report will look like, click the down arrow next to the `Knit` button and choose PDF. 
    - This turns your code file into a PDF report.
    - Do this often to make sure that your code and output is working as intended. 


\newpage

# Part II: Becoming a better learner. 
Because we all have room for improvement, here are a few tasks for you to become a better learner. 


### Metacognition 
From the materials page on the course website, download and read "MAI and academic achievement in college students". 
Once you are done, download and take the "Metacognition Awareness Inventory" (also available on the materials page). 
Submit your scores to Google Drive at this link: https://goo.gl/forms/FYgjJk72T3147e7f1 



### Procrastination
Watch this video on creating a cycle of success and tell me **one** concrete plans of action that you already implement, or are willing to give an honest try to do this semester to stay on track and not fall behind.  https://media.csuchico.edu/media/Avoiding+Procrastination/0_wquy9x90




### Being good at learning is hard!
From the reading materials page on the course website, download and read the "Learning (Your First Job)" article. 
Answer at least _4_ of the following questions in this document. 

**What was the most important insight you gained from the reading? **


**What surprised you most in the reading?**


**What did you already know?**


**Have you been taught how to learn before?  Where?  What did you learn about learning?**


**What will you do differently during a lecture, if anything, given what you read?**


**How will you prepare differently for exams, given what you read?**


**Can you think of other good learning practices that the reading didn't mention?**

\newpage

# PART III: Data Analysis Topic

### Team Formation
Yes yes, you hate group work. But having a person to bounce ideas off of, to help you debug your code, 
to help each other with difficult concepts is an invaluable aspect of learning. So, instead of complaining
make it a goal to be the best analysis partner EVAR! 

If you find yourself unsure how to manage or participate in a group, or you're terrified of working with other people, 
The [University of Minnesota](http://teamwork.umn.edu/) has a fantastic website devoted to surviving group projects.
You will have a group for immediate support in this class, but the project will be done in pairs. 

**Team Roster** Using the numbered list below, write the name of each team member and one interesting fact or tidbit you learned about them this week. Indicate who will be working together on the project.

1.
2. 
3. 
4. 

### Area of research interest
Tell me what data set and topics you are interested in conducting research on and briefly why. If you are using one of the survey data sets (AddHealth, NESARC) that has hundreds or thousands of questions, be specific with the topics and sections that you plan to conduct research in. 


