---
title: 'HW 1: Team Formation & Self Regulated Learning'
author: "Course Number - STUDENT NAME"
date: "Date"
output: pdf_document
---

# Part I: Team Formation

### Team Roster.
Using the numbered list below, write the name of each team member and one interesting fact or tidbit you learned about them this week. Indicate who will be working together on the project. 

1.
2. 
3. 
4. 

### Team Identity


**From henceforth this gathering of people shall be called:** 

\newpage

# Part II: Self Regulated Learning


1. **What was the most important insight you gained from the reading? **


2. **What surprised you most in the reading?**


3. **What did you already know?**


4. **Have you been taught how to learn before?  Where?  What did you learn about learning?**


5. **What will you do differently during a lecture, if anything, given what you read?**


6. **How will you prepare differently for exams, given what you read?**


7. **Can you think of other good learning practices that the reading didn't mention?**

\newpage

# PART III: Analysis Data Set

**State what sections and what data set you are interested in learning more about**


