---
title: "Foundations for Inference"
output:
  html_document:
    highlight: tango
    theme: readable
  pdf_document: default
css: ../css/sandstone.css
---

# Overview

## Assignment Instructions


## Submission Instructions:  

----

# Foundations for Inference

## Sampling distributions
Review Dr. D's analysis of the die rolling exercise. Answer the following questions. Using the die rolling activity to;  

1. explain the difference between a probability distribution and a sampling distribution.
2. Describe the concept of sampling variability.
3. As the sample size increases, describe what happens to the follwing features of the sampling distribution
      - mean:
      - standard deviation: 
      - shape
4. As the number of samples increases, describe what happens to the following of the sampling distribution
      - mean:
      - standard deviation: 
      - shape


## Create your own distribution
### Setup 

1. Open a web browser and go to: https://gallery.shinyapps.io/CLT_mean/
2.	Using the slider on the left side, reduce the sample size to 2, and the number of samples to 10. 
3. Orientation to this interactive app: 
  a. The blue plot at the top is the population distribution of the x’s. 
  b. The smaller plots below are the results of random samples drawn from this population. Each data point (x) is shown as a dot, the vertical bar is the sample mean. 
  c. The green plot at the bottom is a histogram and density plot for the sampling distribution. This is the distribution of the means from each of the samples drawn above.

**Your job** Pick a shape (non-normal, and not uniform) for the population. If you chose a skewed distribution, play around with both a high and a low skew. If you chose a uniform distribution, play around with upper and lower bounds. 

1.	Adjust the number of samples. What happens to the sampling distribution (location/shape/spread)? 


2.	Adjust the sample size. What happens to the sampling distribution (location/shape/spread)? 


3.	At what sample size does the sampling distribution of a low skewed population become approximately normal? 


4.	What about for a distribution with high skew? 

## Confirm the Law of Large Numbers. 




## Explain the Central Limit Theorem
In *your own words*, based on what you have explored through simulation and information in the textbook, what does the Central Limit Theorem say? 




