---
title: "Foundations for Inference"
author: "Student Name"
output:
  pdf_document: default
  html_document: default
---


## Parameters vs Statistics

1. In a study of all 2857 employees at a college, it is found that 45% own a vehicle.
**TRUE OR FALSE**: The number 45% is a parameter. 


2. In a survey, one hundred college students are asked how many hours per week they spend on the Internet. 
**TRUE OR FALSE**: The parameter of interest is a proportion.



3. In a survey, smart phone users are asked how many times they used a web-based taxi service over the last year. 
**TRUE OR FALSE**: The parameter of interest is a proportion.



4. In a survey, one hundred college students are asked whether or not they cited information from Wikipedia in their papers. **TRUE OR FALSE**: The parameter of interest is a proportion.



5. Suppose you want to estimate the percentage of videos on YouTube that are cat videos. It is impossible for you to watch all videos on YouTube so you use a random video picker to select 1000 videos for you. You find that 2% of these videos are cat videos. **TRUE OR FALSE**: A video in your sample is a sample statistic. 




## Sampling distributions

1. explain the difference between a probability distribution and a sampling distribution.


2. Describe the concept of sampling variability.


3. As the sample size increases, describe what happens to the following features of the sampling distribution
      - mean:
      - standard deviation: 
      - shape


4. As the number of samples increases, describe what happens to the following of the sampling distribution
      - mean:
      - standard deviation: 
      - shape


## Scale up
1.	Adjust the number of samples. What happens to the sampling distribution (location/shape/spread)? 


2.	Adjust the sample size. What happens to the sampling distribution (location/shape/spread)? 


3.	At what sample size does the sampling distribution of a low skewed population become approximately normal? 


4.	What about for a distribution with high skew? 


## Explain the Central Limit Theorem
Using the continuous variable you worked with on the Foundations worksheet, explain to someone else what the Central Limit Theorem tells you about the sampling distribution. But don't use fancy technical terms. For example if you were researching a person's age, describe the distribution of the individual ages, and the distribution of the average age (complete with numbers). 


