---
output:
  html_document:
    highlight: tango
    theme: readable
    toc: yes
    toc_float: yes
css: ../css/customh5.css
params:
    w: 5
    d: '2018-09-24'
title: "Week `r params$w`: `r format(as.Date(params$d) ,'%b %d')` - `r format(as.Date(params$d)+6 ,'%b %d')`"
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(dplyr);library(readxl); library(knitr)
library(kableExtra); library(stringr)
knitr::opts_chunk$set(echo = FALSE)
options(knitr.table.format = "html", knitr.kable.NA = '') 
```

_Last Updated: `r format(Sys.time(), "%a %b %d %X")` _  
Back to the [[Schedule]](../schedule.html)
<br>

```{r echo=FALSE, message=FALSE, warning=FALSE}
# Read in schedule and extract this week
raw <- read_excel("../schedule_315.xlsx")
week.w <- filter(raw, wk==params$w)

# update relative paths
week.w[,6:10] <- gsub("reading/", "../reading/", week.w[,6:10]) 
week.w[,6:10] <- gsub("lecture/", "../lecture/", week.w[,6:10]) 
week.w[,6:10] <- gsub("hw/", "../hw/", week.w[,6:10]) 

  
# strip columns into separate data sets
topics <- t(str_split(week.w$Topics, "\r\n", simplify=TRUE))
SLO    <- paste("*", str_split(week.w$SLO, "\r\n", simplify=TRUE))
prep   <- paste("*", str_split(week.w$Prepare, "\r\n", simplify=TRUE))
mats   <- paste("*", str_split(week.w$Materials, "\r\n", simplify=TRUE))
hw     <- paste("*", str_split(week.w$Assignments, "\r\n", simplify=TRUE))
mon    <- t(str_split(week.w$Monday, "\r\n", simplify=TRUE))
wed    <- t(str_split(week.w$Wednesday, "\r\n", simplify=TRUE))
fri    <- t(str_split(week.w$Friday, "\r\n", simplify=TRUE))
```

----

# Learning Objectives
```{r}
x <- kable(SLO) %>% kable_styling(bootstrap_options = c("striped", "condensed"))
gsub("<thead>.*</thead>", "", x)
```

#Prepare
```{r}
x <- kable(prep) %>% kable_styling(bootstrap_options = c("striped", "condensed"))
gsub("<thead>.*</thead>", "", x)
```

# Materials
```{r}
x <- kable(mats) %>% kable_styling(bootstrap_options = c("striped", "condensed"))
gsub("<thead>.*</thead>", "", x)
```

# Assignments
```{r}
x <- kable(hw) %>% kable_styling(bootstrap_options = c("striped", "condensed"))
gsub("<thead>.*</thead>", "", x)
```


----

# Monday: `r topics[1]`

```{r}
kable(mon) %>% kable_styling(bootstrap_options = c("striped", "condensed"))
```


# Wednesday: `r topics[2]`

```{r}
kable(wed) %>% kable_styling(bootstrap_options = c("striped", "condensed"))
```

# Friday: `r topics[3]`

```{r}
kable(fri) %>% kable_styling(bootstrap_options = c("striped", "condensed"))
```


